Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,26 +40,26 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           
-      - name: Coverity SAST Scan
-        run: |
-          cov-capture --dir idir --project-dir .
-          cov-analyze --dir idir --ticker-mode none --webapp-security --all
-          cov-commit-defects --dir idir --ticker-mode none --url ${{ secrets.COVERITY_URL }} --on-new-cert trust --stream HVP_vulpy
-          
-      - name: Coverity Security Gate
-        run: |
-          curl.exe -u ${{ secrets.COVERITY_USER }}:${{ secrets.COVERITY_PASSPHRASE }} -o security-gate-results.json ${{ secrets.COVERITY_URL }}/api/viewContents/issues/v1/High%20Impact%20Outstanding?projectId=HVP_vulpy
-          if ($(type security-gate-results.json | jq .viewContentsV1.totalRows) -ne 0 )
-          {
-            echo Security gate found policy violations
-            ## type security-gate-results.json | jq .viewContentsV1.rows
-            ## You may mark the build as failure
-            ##exit 1;
-          }
-          else
-          {
-            echo No High Impact issues policy violations found
-          }
+#      - name: Coverity SAST Scan
+#        run: |
+#          cov-capture --dir idir --project-dir .
+#          cov-analyze --dir idir --ticker-mode none --webapp-security --all
+#          cov-commit-defects --dir idir --ticker-mode none --url ${{ secrets.COVERITY_URL }} --on-new-cert trust --stream HVP_vulpy
+#          
+#      - name: Coverity Security Gate
+#        run: |
+#          curl.exe -u ${{ secrets.COVERITY_USER }}:${{ secrets.COVERITY_PASSPHRASE }} -o security-gate-results.json ${{ secrets.COVERITY_URL }}/api/viewContents/issues/v1/High%20Impact%20Outstanding?projectId=HVP_vulpy
+#          if ($(type security-gate-results.json | jq .viewContentsV1.totalRows) -ne 0 )
+#          {
+#            echo Security gate found policy violations
+#            ## type security-gate-results.json | jq .viewContentsV1.rows
+#            ## You may mark the build as failure
+#            ##exit 1;
+#          }
+#          else
+#          {
+#            echo No High Impact issues policy violations found
+#          }
       
       - name: Black Duck SCA Scan
         run: |
@@ -69,7 +69,7 @@ jobs:
           type PROJECT_NAME
           type VERSION_NAME
           
-          powershell "[Net.ServicePointManager]::SecurityProtocol = 'tls12'; irm https://detect.synopsys.com/detect7.ps1?$(Get-Random) | iex; detect" --blackduck.url=${{ secrets.BLACKDUCK_URL }} --blackduck.api.token=${{ secrets.BLACKDUCK_API_TOKEN }} --blackduck.trust.cert=true --detect.policy.check.fail.on.severities=BLOCKER --detect.project.name=$PROJECT_NAME --detect.project.version.name=$VERSION_NAME
+#          powershell "[Net.ServicePointManager]::SecurityProtocol = 'tls12'; irm https://detect.synopsys.com/detect7.ps1?$(Get-Random) | iex; detect" --blackduck.url=${{ secrets.BLACKDUCK_URL }} --blackduck.api.token=${{ secrets.BLACKDUCK_API_TOKEN }} --blackduck.trust.cert=true --detect.policy.check.fail.on.severities=BLOCKER --detect.project.name=$PROJECT_NAME --detect.project.version.name=$VERSION_NAME
 
 #      - name: Black Duck SCA Scan
 #        uses: synopsys-sig/detect-action@main
